config/routes.rb
Rails.application.routes.draw do
  get 'pokemon_speed' => 'speeds#home'
  get 'api/greeting' => 'application#test'
  get 'api/characters' => 'application#message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
end

app/models/speed.rb
class Speed < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def test
    # messages = params[:message]
    # render json: {message: "#{messages}!"}
    # if messages = "hello"
    #   render json: {message: "hello!"}
    # elsif messages = "morning"
    #   render json: {message: "morning!"}
  end
  def message
    messages = params[:q]
    render json: {characters: Character.where("name like '%#{messages}%'")}
  end
end

app/controllers/speeds_controller.rb
class SpeedsController < ApplicationController
  def home
    @character = Character.all
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speed_helper.rb
module SpeedHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpeedApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/speeds/home.html.erb
<h1>ポケモンソード・シールド素早さ計算ツール</h1>
<div class="wrapper">
  <div class="myself_container">
    <div class="search_foram">
      <%= form_tag(pokemon_speed_path, method: :get, enforce_utf8: false, class: "name_search_form") do %>
        <div>
          <select class="js-data-example-ajax" style="width: 100%"></select>
        </div>
        <div>
          種族値：<input type="text" name="race_speed" class="character_race_speed" id="race_value">
        </div>
        個体値：<select id="iv0" tabindex="2"><option value="31" selected="selected">31</option><option value="30">30</option><option value="29">29</option><option value="28">28</option><option value="27">27</option><option value="26">26</option><option value="25">25</option><option value="24">24</option><option value="23">23</option><option value="22">22</option><option value="21">21</option><option value="20">20</option><option value="19">19</option><option value="18">18</option><option value="17">17</option><option value="16">16</option><option value="15">15</option><option value="14">14</option><option value="13">13</option><option value="12">12</option><option value="11">11</option><option value="10">10</option><option value="9">9</option><option value="8">8</option><option value="7">7</option><option value="6">6</option><option value="5">5</option><option value="4">4</option><option value="3">3</option><option value="2">2</option><option value="1">1</option><option value="0">0</option></select>
        努力値：<input _ngcontent-rmu-c3="" id="Effort_value"class="number digits-3 ng-valid ng-dirty ng-touched" max="252" min="0" step="4" type="number" value = "252">
        性格補正値：<select id="nature0" tabindex="3"><option value="1.1" selected="selected">1.1倍</option><option value="1">1.0倍</option><option value="0.9">0.9倍</option></select>
        実数値：<input type="text" id="speed_value">
      <% end %>
    </div>
  <div>
<div>